p-ranav/argparse

include/argparse.hpp
I fixed some warnings I was getting on GCC 8.3.0 while using the following flags:
`-Wold-style-cast -Wshadow`
- Changed usage of `(char*)arg.data()` to `const_cast<char*>(arg.data())`
- `tIterator` is defined with the same type a few times so I just made it reassign instead of re-declare.
After running the tests, they all seem to pass and the warnings are gone. If I've messed anything up, just let me know.
=> Fix some warnings

include/argparse.hpp
On my opinion you should never call `exit` in library code since it is quite difficult for the user to handle this in his application and perform a proper shutdown. Further it is not obvious from your API that the simple parse_args call my exit your whole program.
Further I put your error message into the exceptions to let the application developer decide how the should be logged.
=> Replaced exit(0) by std::runtime_error

include/argparse.hpp
Fixed a warning I was getting on GCC 8.3.0 with `-Wsign-conversion` enabled.
- Changed `std::accumulate(std::begin(names), std::end(names), 0...` to `std::accumulate(std::begin(names), std::end(names), std::string::size_type{0}...`
I usually find it's best to be explicit with the type you pass to `std::accumulate` as it uses the type it infers as the starting number so it can be a source of pesky bugs.
If you're curious, I use a lot of warning flags when working with code:
```
-Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-include-dirs -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-overflow=5 -Wundef -Wno-unused
```
=> Fix warning shown with -Wsign-conversion.

include/argparse.hpp
Sometimes people use a const qualifier in their definition of main like so:
```cpp
int main(int argc, const char** argv);
```
Currently, the compiler (GCC 8.3.0) with _no extra flags_ will complain about a conversion error from `const char**` -> `char**`.
This PR addresses the problem by allowing _both_ definitions of main so there is no compatibility breaking.
=> Allow use of both const char** and char** for argv.

include/argparse.hpp, test/test_compound_arguments.hpp, test/test_container_arguments.hpp, test/test_utility.hpp
- Use a single function for container types for
- Argument::get
- Argument::operator==
- throw std::logic_error instead of returning default value in Argument::get
=> Unify Argument::get and Argument::operator== for container types

include/argparse.hpp, test/test_compound_arguments.hpp, test/test_invalid_arguments.hpp, test/test_positional_arguments.hpp
Simplified structure of arg parsing using stl algorithms to improve readability, maintainability and extendability.
The only drawback is that optional arguments may no longer occur in between arguments belonging to the same positional argument (compare changed tests). But on my oppinion this should not really be a use case.
=> Simplify structure of parse_args_internal

CMakeLists.txt
Modify the CMakeLists.txt file to properly generate config file.
The `/include` string part intended for BUILD_INTERFACE was added
after the generator expression itself, which resulted
in extra `/include` path INTERFACE_INCLUDE_DIRECTORIES property
of exported configuration.
=> Fix invalid cmake export configuration

include/argparse.hpp
If an argument is required and it
- doesn't have a default value and is not set. => exception
- doesn't have a default value and is set without any value. => exception
- doesn't have a default value and is set with some value. => use the value provided.
- has a default value and is set without any value. => exception
- has a default value and is set with some value. => use the value provided.
If an argument is not required, nothing changes.
I will add some tests later.
Also see #27.
=> Add a 'required' feature

include/argparse.hpp
In current version, anonymous namespace can't guarantee that helper methods are invisible outside this header file.
For example, there are two files:
```cpp
// test.hpp
namespace test {
namespace {
int var = 0;
}
}
```
```cpp
// test.cpp
#include <iostream>
#include "test.hpp"
using namespace test;
using namespace std;
int var = 1;
int main()
{
cout << var << endl;
return 0;
}
```
Then we run `clang++ test.cpp`.
We will get the error.
So I add a name for the anonymous namespace to avoid errors when naming conflicts.
=> Add a name for the anonymous namespace

include/argparse.hpp
=> Remove the undocumented PARSE_ARGS macro

include/argparse.hpp, test/test_actions.hpp
Hi,
I'm not sure about how side-effects-only actions should interact with default values etc.  I'm trying to not let it overrides default values.  Code owner please check.
closes: p-ranav/argparse#39
=> Allow actions that return void

.clang-format, include/argparse.hpp, test/test_actions.hpp
The semantics I chose here is slightly different from `std::bind_front` but is as same as `std::bind` (with a much simpler codegen though) -- the bounded arguments unwrap `std::reference_wrapper`.  Long story short, I think the rationale in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1651r0.html doesn't apply to our case, because the intermediate partial-application objects do not escape argparse.
When binding member calls, `.action(&Class::fn, std::ref(obj))` and `.action(&Class::fn, &obj)` both work.  Pedantic people may not like the later because `operator&` may be overloaded.
It would be fun to use one example to demo both void-actions and partial applications.
closes: p-ranav/argparse#38
=> Bind in action

README.md, include/argparse.hpp, test/main.cpp, test/test_parent_parsers.hpp, test/test_value_semantics.hpp
Python `argparse.ArgumentParser` is stateless, so adding parents is only inheriting argument configurations.  This is equivalent to having value semantics.
`argparse::ArgumentParser` is stateful.  Instead of returning parsed states, `parse_args` changes the parser's own states.  And I think we should also deliver value semantics, that is, `parse_args` in child parser does not change parents' parsing states, and `parse_args` in a parser copy does not change the parsing states parser that was copied from.
Updated the docs to use the term "common" rather than "shared" to clarify the intention.
Strictly speaking this is a runtime breaking change.  But the current behavior is undocumented, untested, and I doubt anybody is relying on that in real code.
The proposed change also eliminates the …
=> Value semantics

include/argparse.hpp, test/test_optional_arguments.hpp
In a process of cleaning up some crufts, I found a bug and had to fix it.  As a result, the proposed change, if merged, will allow `add_argument`, `operator[]`, and `get()` to freely mix the uses of `const char*`, `std::string`, and `std::string_view`.
See the last commit's message for details.
=> Cleanup & allow creating and accessing arguments with string_view

include/argparse.hpp
SFINAE is only useful as constraints.  A overload set that works for all `T`, no matter `Predicate<T>` is true or false, is effectively unconstrained.  Constexpr if statements work better in that case.
This change also eliminates the last two warnings in MSVC, surpressed a stupid Codacy warning, and fixed a two minor issues (redundant any, missed constraint).
=> Finishing cleanup by refactoring SFINAE into constexpr-if

include/argparse.hpp, test/test_actions.hpp, test/test_optional_arguments.hpp, test/test_positional_arguments.hpp
This kind of argument works as if having the "remaining" nargs,
inspired by Python's `argparse.REMAINDER`.
This change also reduces the size of `Argument` by 8 bytes.
See also: https://docs.python.org/2/library/argparse.html#nargs
PS1: document is missing, but in the unit test there is a test case "sum" for helping forming an official example.
PS2: after resolving #56, I think that's enough features for the next release.  Thoughts?
fixes: p-ranav/argparse#17
=> Support capturing remaining() arguments

test/CMakeLists.txt, test/main.cpp, test/test_actions.cpp, test/test_compound_arguments.cpp, test/test_container_arguments.cpp, test/test_help.cpp, test/test_invalid_arguments.cpp, test/test_issue_37.cpp, test/test_negative_numbers.cpp, test/test_optional_arguments.cpp, test/test_parent_parsers.cpp, test/test_parse_args.cpp, test/test_positional_arguments.cpp, test/test_required_arguments.cpp, test/test_value_semantics.cpp
This change also explicitly lists the source files
for CMake.  This is because `GLOB` does not remove
old files when switching branches in Git, and
`CONFIGURE_DEPENDS` will add unstaged files after
stashing.
See also: https://cmake.org/cmake/help/latest/command/file.html#glob
(I can add the `DOCTEST_` prefix back if you like it;
but don't think it matters though, every unit test
framework uses `TEST_CASE`...)
PS: how to use:
`build/test/tests -ltc` -- list test cases
`build/test/tests -lts` -- list test suites
`build/test/tests -ts=actions`  -- run all tests in `test_suite("actions")`
=> Annotate test cases with doctest::test_suite

include/argparse.hpp
Emergent.  The deprecated (therefore untested) `print_help` wasn't printing anything because reading from `ostringstream` is allowed but does nothing.  Sorry about this negligence.
=> Fix print_help for printing nothing

include/argparse.hpp, test/test_help.cpp
The change also fixes a rare bug introduced in 9007958:
when there are duplicated keys, insert_or_update overrides
previously inserted ones, emplace doesn't.
fixes: p-ranav/argparse#59
=> Default --help to print help and exit

include/argparse.hpp, test/test_negative_numbers.cpp
Two differences that diverge from the existing behavior:
1. Leading zeros are not allowed for integers.  Negative
octal numbers such as `-066` are not meant to be treated
as positional arguments, but existing code recognize them
as decimal numbers.  Note that negative floating-point
numbers with leading zeros (`-003.`) are unambiguous and
are recognized.
2. Inf and NaN are not recognized.  This is because options
like `-inf` is indistinguishable from a compound argument
that meant to be a shorthand for `-i -n -f`.
fixes: p-ranav/argparse#55
=> Determine negative numeric values with a grammar

.travis.yml, README.md, include/argparse.hpp, test/CMakeLists.txt, test/test_scan.cpp
Limitations due to portability :
1. This patch uses `from_chars` for parsing integer numbers.  To do so, I bumped required GCC version to 8.x and required Clang/libc++ version to 7.x.
2. This patch emulates `from_chars` behavior for parsing floating-point numbers with `strtod`, but this function is locale-aware.
3. The emulation does not use strict grammar to distinguish fixed and scientific format.  As a result, `NAN(char_sequence)` (signal NaN, but should be parsed as quiet NaN) may fail to parsed.
Caveats:
1. There is no `base == 0` case for `from_chars`; integer format detection for `'i'` shape is done by hand.
2. Hexfloat is not considered possibly negative as positional argument, so negative hexfloat currently is not a valid input.
3. `+` sign is not allowed, but this is a result of …
=> Simplify parsing numeric arguments with .scan

README.md, include/argparse.hpp, test/test_parse_args.cpp
=> Get arguments in optional<T> with .present<T>()

include/argparse.hpp
One less `enable_if`.
Line 774 has a Clang bug involved (fixed in Clang 8).  The array bound isn't necessary here.
=> Simplify a few internals

include/argparse.hpp
It would be nice to add text to the beginning and end of help messages. Many standard *nix tools do this to provide examples, show license information, etc.
For example, the current help output on a firmware programmer I am building:
```
Usage: dev-program [options] FILE
Positional arguments:
FILE                    HEX input file
Optional arguments:
-h --help               show this help message and exit
-l --list-interfaces    List all possible programming interfaces detectable by this program
-d --delay              Amount of time to wait for a device reset for programming, in milliseconds (default 5000)
-r --auto-reset         Attempt to automatically reset the device (depends on programming cable and/or current firmware)
```
Turns into:
```
Usage: dev-program [options] FILE
Internal …
```
=> Add the option to add text before and after help output

include/argparse/argparse.hpp
Previously, it printed ": expected 1 argument(s). 0 provided." when one positional argument is defined but nothing is provided. Now it prints "1 argument(s) expected. 0 provided."
=> Fix incorrect message when mUsedName is empty

include/argparse/argparse.hpp
Propose, skip text `[Required]` if argument has default value,
because the argument can be omitted in commend-line.
=> Fix help if required and def-value. Fixes #89.

include/argparse/argparse.hpp
Insert a space between argument's help message and text `[required]`.
Also move if-else clauses around a little to not duplicate `argument.mDefaultValue.has_value()`.
=> nicer usage text for required arg

include/argparse/argparse.hpp
Motivated by wanting to avoid ADL failure (e.g. when another `#include ...` specifies a free `begin()`/`end()`).
=> Qualify iterator functions

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_append.cpp
The default behavior with optional arguments is to allow only a single use
per invocation.  One alternative is to use .nargs, but this requires
previously knowing, and limiting, the quantity of values.  The .append
method removes the restriction on repeats for a single Argument.
=> Add Argument.append method to allow repeated argument use

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_is_used.cpp
.present returns std::nullopt if the optional argument is not given by the
user -- as long as a .default_value is not defined.  With a .default_value,
.present cannot be used to determine if a value is user-provided or the
default.
.is_used fills that role and only returns true if the argument was passed
by the user.
=> Add ArgumentParser.is_used to discern user-supplied values from defaults

CMakeLists.txt, include/argparse/argparse.hpp
Per https://github.com/p-ranav/argparse/issues/102 -- introduces a compiler directive to allow "--version" to be restricted to the long-form only, and a CMakeLists.txt option for controlling it.
Example with it disabled:
```cmake
set (ARGPARSE_LONG_VERSION_ARG_ONLY ON)
add_subdirectory(argparse)
```
produces:
```
> .\build\cparse\cparse.exe --help
Usage: cparse [options]
Optional arguments:
-h --help       shows help message and exits
--version       prints version information and exits
-v --verbose    Increase output verbosity
-q --quiet      Decrease output verbosity
-G --gui        Enable GUI [default: false]
```
where as without this option on:
```
> .\build\cparse\cparse.exe --help
Usage: cparse [options]
Optional arguments:
-h --help       shows help message and exits
-v --version …
```
=> Allow user to limit version argument to --version

include/argparse/argparse.hpp
https://github.com/p-ranav/argparse/pull/109#issuecomment-892943775
=> Replace size_t to std::size_t.

include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_const_correct.cpp, test/test_value_semantics.cpp
Hi!
I wished to provide a small contribution to your fine project.
In another project I am currently working on, I stumbled upon a minor inconvenience in `argparse`'s interface. Normally after parsing the parameters one would expect the parser to be immutable (quite understandably so in simple cases). However, I realized a crucial function checking for a value being actually passed by the user is not, though could be, `const`!
I am concerned the test I wrote might actually be meaningless. What one would expect there is for the code to actually compile, nothing more, to validate this change. I could also offer rewriting some tests to try to better comply with `ArgumentParser`'s immutability at some point in their bodies, if you deem that viable or useful in any way.
Cheers!
=> Const-correct ArgumentParser

include/argparse/argparse.hpp
I think we're clear to use stdlib. @lichray may say this is not yet appropriate.
=> Use std::chars_format rather than local copy

.github/workflows/ci.yml
Run tests on Apple macOS, MS Windows, and Ubuntu Linux hosts.
macOS-hosted tests are only run on latest, which is currently macOS 10.15.
GH will eventually update latest to macOS 11 and we can look at expanding
to two versions of macOS.
Windows-hosted tests run on Windows Server 2016 and latest.
Ubuntu-hosted tests only run on latest because g++ fails to build argparse
on ubuntu-18.04 (GCC 8) since charconv was added in commit ea2f16d2.  But,
Ubuntu-hosted tests do run with g++ and clang++.
Closes #128.
=> Add GitHub Action to run tests on pull request

test/CMakeLists.txt
This silences the following warning:
No project() command is present.  The top-level CMakeLists.txt file must
contain a literal, direct call to the project() command.  Add a line of
code such as
project(ProjectName)
near the top of the file, but after cmake_minimum_required().
CMake is pretending there is a "project(Project)" command on the first
line.
=> Add CMake project name

include/argparse/argparse.hpp
As mentioned in https://github.com/p-ranav/argparse/issues/87, I also think it'd better that get("out") is also available to "--out" option, for example.
Actually, I made this kind of mistake many times because with Python argparse, this syntax is OK.
In this pull request, I made get syntax more flexible this way.
Additionally, now thrown logic_error.what() kindly shows what argument is invalid to make debug easier.
=> Make get syntax flexible

README.md
The examples provided in README initially showed printing error messages to stdout instead of stderr and exited with 0. I changed them to print to stderr and to exit with code 1 similar to what Linux does when it encounters similar errors.
=> Modify README.md to show printing errors to stderr instead of stdout

include/argparse/argparse.hpp, test/test_invalid_arguments.cpp, test/test_version.cpp
Now message contains information which argument is the source of error.
It's easier to spot typo/understand which part of more complex command
is the source of problem.
=> Improve thrown message in case of invalid argument.

.github/workflows/ci.yml
The Windows Server 2016 test environment is scheduled for removal on
March 15, 2022.
=> Remove Windows Server 2016 from test matrix

.clang-format, .clang-tidy, include/argparse/argparse.hpp
=> Enable clang-tidy readability-braces-around-statements check

include/argparse/argparse.hpp
This regression was caused by commit
ea1f7ef663899e799001f50055cc93c733a9fff, which didn't add "\n" to the
version printing statement. We use std::endl now for compatibility
across platforms.
=> Fix regression in version printing.

include/argparse/argparse.hpp
Solution suggested by skrobinson. This way, GCC and clang-tidy don't
generate warnings.
Fixes: https://github.com/p-ranav/argparse/issues/167
=> Fix unused argument warnings.

test/doctest.hpp
Fixes the build error on latest GNU/Linux Systems: (https://github.com/doctest/doctest/issues/473)
Source for doctest.hpp has been updated from this url: (https://raw.githubusercontent.com/onqtam/doctest/v2.4.8/doctest/doctest.h)
=> Updates doctest from v2.3.5 to v2.4.8

include/argparse/argparse.hpp
Commit 5c5c55b83cc7d542890a47aeee6530a8ee6d10f7 missed one such
occurrence.
=> Fix remaining unused argument warnings.

include/argparse/argparse.hpp
After upgrading g++ package to 12.1.0 on archlinux I see the following
compilation error:
/usr/include/argparse/argparse.hpp: In member function ‘void argparse::ArgumentParser::index_argument(list_iterator)’:
/usr/include/argparse/argparse.hpp:1167:34: error: ‘as_const’ is not a member of ‘std’; did you mean ‘is_const’?
1167 |     for (const auto &name : std::as_const(it->m_names)) {
|                                  ^~~~~~~~
|                                  is_const
It turns out that std::as_const comes from <utility> header [1] which
was not explicitly included.
[1] https://en.cppreference.com/w/cpp/utility/as_const
=> Add missing <utility> include

README.md, include/argparse/argparse.hpp, test/test_actions.cpp, test/test_optional_arguments.cpp, test/test_positional_arguments.cpp
Hi.
Thank you for this nice library.
I see some issues regarding "remaining" behavior.
https://github.com/p-ranav/argparse/issues/118
https://github.com/p-ranav/argparse/issues/81
I also wanted optional argument preceded by variable length positional arguments (including zero length) like Python argparse nargs "*", "+", "?"
So, I implemented it just for experiment.
For now, this worked for me.
I know this change drops "remaining" feature, which would impact existing projects.
Also, this seems a complicated problem and I think more study may be needed.
What do you think about this change?
Thank you in advance.
=> Improve nargs

README.md
I added a small section to the readme about using the latest argparse in a cmake project. The rather new cmake functionality FetchConent allows accessing external resources without copying anything manually. Personally I like that approach.
Feel free to decline. And thank your for writing argparse!
Adrian
=> Extend Readme with CMake FetchContent integration of argparse.

include/argparse/argparse.hpp
such that it matches the corresponding documentation:
https://github.com/p-ranav/argparse#adding-a-description-and-an-epilog-to-help
=> Add empty line above epilog

.github/workflows/ci.yml, include/argparse/argparse.hpp
There have been hosting changes and we could expand to more test environments.
=> Update CI hosts and fix clang-cl build

include/argparse/argparse.hpp
This PR optimizes 'get' by returning references as opposed to values. This decreases the theoretical memory usage by 50% since values are no longer passed by value. This also let's the compiler free to optimize these calls since L-values are not returned for non-containers.
=> Use references for any_cast

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_parse_known_args.cpp
Closes #181 
This PR adds a `parse_known_args` support.
Sometimes a program may only parse a few of the command-line arguments, passing the remaining arguments on to another script or program. In these cases, the `parse_known_args()` function can be useful. It works much like `parse_args()` except that it does not produce an error when extra arguments are present. Instead, it returns a list of remaining argument strings.
```cpp
#include <argparse/argparse.hpp>
#include <cassert>
int main(int argc, char *argv[]) {
program.add_argument("--foo").implicit_value(true).default_value(false);
program.add_argument("bar");
auto unknown_args =
program.parse_known_args({"test", "--foo", "--badger", "BAR", "spam"});
assert(program.get<bool>("--foo") == true); …
```
=> parse_known_args

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_prefix_chars.cpp
This PR adds support for custom `prefix_chars` and `assign_chars`
Most command-line options will use `-` as the prefix, e.g. `-f/--foo`. Parsers that need to support different or additional prefix characters, e.g. for options like `+f` or `/foo`, may specify them using the `set_prefix_chars()`.
The default prefix character is `-`.
```cpp
#include <argparse/argparse.hpp>
#include <cassert>
int main(int argc, char *argv[]) {
program.set_prefix_chars("-+/");
program.add_argument("+f");
program.add_argument("--bar");
program.add_argument("/foo");
try {
program.parse_args(argc, argv);
}
catch (const std::runtime_error& err) {
std::cerr << err.what() << std::endl;
std::cerr << program;
std::exit(1);
}
if (program.is_used("+f")) {
std::cout << "+f    : " …
```
=> Closes #67: option-value syntax support

samples/compound_arguments.cpp, samples/custom_assignment_characters.cpp, samples/custom_prefix_characters.cpp, samples/description_epilog_metavar.cpp, samples/gathering_remaining_arguments.cpp, samples/is_used.cpp, samples/joining_repeated_optional_arguments.cpp, samples/list_of_arguments.cpp, samples/negative_numbers.cpp, samples/optional_flag_argument.cpp, samples/parse_known_args.cpp, samples/positional_argument.cpp, samples/repeating_argument_to_increase_value.cpp, samples/required_optional_argument.cpp, samples/subcommands.cpp
I'm a big fan of the samples directory. Personally, I learn APIs better from examples than specification docs.
I expect many people will copy and paste from the samples to start their own code. This is a good thing.
Therefor, I'd like to see explicit, per-file licenses on these samples.
=> Add an explicit MIT license to each sample source file

include/argparse/argparse.hpp, test/test_positional_arguments.cpp
This tries to fix #208 by printing which argument is reporting the missing parameter.
=> Fix issue 208

.github/workflows/tidy-analysis-stage-01.yml, .github/workflows/tidy-analysis-stage-02.yml
I found an alternate to the previously tried `JacobDomagala/StaticAnalysis`. `platisd/clang-tidy-pr-comments` only offers `clang-tidy` checks, but provides security-compatible use patterns that will allow running checks with PRs from forks.
See an example at skrobinson/argparse/pull/8. I'm hoping this action will work as nicely with forks as the example works with branches.
=> Add clang-tidy analysis of pull requests

include/argparse/argparse.hpp
This fixes `get<T>()` (and by extension `operator==`) for situations where a value is stored as a `std::string_view`.
=> Fix std::string_view being identified as a container

README.md, include/argparse/argparse.hpp, test/test_subparsers.cpp
It's useful for removing string literals duplication in a code.
=> Add is_subcommand_used overload

include/argparse/argparse.hpp
Added a fix for issue #235.
For the following code:
```
#include <argparse/argparse.hpp>
int main(int argc, char *argv[]) {
argparse::ArgumentParser program("foo", "1.0", argparse::default_arguments::none);
program.add_argument("-h", "--hint");
program.add_argument("-v", "--verbose");
program.add_argument("--bar");
std::cout << program.usage();  // Usage: foo [--hint VAR] [--verbose VAR] [--bar VAR]
return 0;
}
```
the output now is:- `Usage: foo [--hint VAR] [--verbose VAR] [--bar VAR]`
Thanks
=> Added a fix for issue #235

.clang-tidy, .github/workflows/tidy-analysis-stage-01.yml
These changes limit clang-tidy checks to the main header.
=> Fix tidy checks

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_as_container.cpp
This allows updating attached object properties without holding external references to the various Argument and ArgumentParser objects.
Closes #227
=> Add ArgumentParser::at to retrieve arguments and subparsers

README.md
This tries to bring a little more attention to the option to remove default arguments.
=> Highlight default arguments and their default behavior

CMakeLists.txt
Per https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#exporting-targets this is the standard way to do so, no need to hack CMAKE_INSTALL_LIBDIR_ARCHIND
=> Install cmake export file in CMAKE_INSTALL_DIR

include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_default_value.cpp
Closes #249
Reported-by: @pfeatherstone
=> Fix crash with char[] default values

include/argparse/argparse.hpp
Hi @p-ranav 
I  really liked the API of this project, thank you for sharing your work
It helped me a lot.
However, I couldn't compile it at first. 
This merge request fixes the issue
The problem was similar to this one https://github.com/microsoft/cppwinrt/issues/479
Hope it helps someone too
Happy coding 😄
=> Resolves the std::numeric_limits<std::size_t>::max)()} error

README.md, include/argparse/argparse.hpp, samples/compound_arguments.cpp, samples/custom_assignment_characters.cpp, samples/custom_prefix_characters.cpp, samples/gathering_remaining_arguments.cpp, samples/is_used.cpp, samples/joining_repeated_optional_arguments.cpp, samples/list_of_arguments.cpp, samples/negative_numbers.cpp, samples/optional_flag_argument.cpp, samples/positional_argument.cpp, samples/required_optional_argument.cpp, samples/subcommands.cpp, test/test_default_args.cpp
This PR tries to resolve the discussions in #251.
=> Add exit_on_default_arguments parameter to ArgumentParser

include/argparse/argparse.hpp, test/test_help.cpp
This PR fixes #248 by aligning multiline help messages. A previous PR, #259, attempted to fix the issue, but it was not finalized due to unresolved clang-tidy issues. This PR builds upon the work done in PR #259 and addresses the outstanding issues.
The key changes in this PR include:
1. Using spaces instead of `"\t"` to separate argument names and help messages. This makes the spacing independent of the terminal's tab width settings and simplifies testing.
2. Adding a test case to verify that all help messages are properly aligned.
Additionally, while working on this issue, I noticed that the `-DCMAKE_CXX_STANDARD=17` flag is required when using CMake to build the test. This flag is currently not documented in the README:
https://github.com/p-ranav/argparse/blob/557948f1236db9e27089959de8 …
=> Fix issue #248: Align multiline help messages

include/argparse/argparse.hpp
Hi, I'd like to provide this little implementation regarding column-aligned multi-line help message that works for arguments (not subcommands). This was discussed in https://github.com/p-ranav/argparse/issues/248 but the original poster didn't open a pull request.
In test_help.cpp I didn't see a test that validates the help message on a per-character level, so I didn't write any test.
=> implements column-aligned multi-line help message for arguments

CMakeLists.txt, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_help.cpp
CMakefile: Use -Wpedantic, -Werror and -Wextra for compilation in gcc. Fixed warnings
=> CMakefile: Use -Wpedantic, -Werror and -Wextra for compilation in gcc. Fixed warnings

README.md
It's imporant to note that FetchContent will automatically build all of the argparse tests and samples when including it with FetchContent, since the root CMakeLists.txt file sets these options as ON by default.
Generally, users of the library wouldn't want tests and samples to be built alongside a library dependency, so we could include these two more lines in the README to show how to disable building the tests and samples by default.
=> Add to readme cmake FetchContent section 

README.md, samples/compound_arguments.cpp, samples/custom_assignment_characters.cpp, samples/custom_prefix_characters.cpp, samples/gathering_remaining_arguments.cpp, samples/is_used.cpp, samples/joining_repeated_optional_arguments.cpp, samples/list_of_arguments.cpp, samples/negative_numbers.cpp, samples/optional_flag_argument.cpp, samples/positional_argument.cpp, samples/required_optional_argument.cpp, samples/subcommands.cpp
parse_args can throw exceptions that are not based on std::runtime_error, and the error message should show on all errors.
For example, if a user is using a program formatted as:
```cpp
parser.add_argument("number")
.help("Enter a number")
.scan<'i', int>();
try {
parser.parse_args(argc, argv);
} catch (const std::runtime_error &e) {
std::cerr << e.what() << std::endl;
std::cerr << parser;
return EXIT_FAILURE;
}
```
and the user messes up by misformatting the "number" positional argument, this will throw an std::invalid_argument from argparse::details::do_from_chars. However, [std::invalid_argument inherits from std::logic_error, not std::runtime_error](https://en.cppreference.com/w/cpp/error/invalid_argument), so the user will just have an aborted program with no help message. In order …
=> Change parse_args readme and samples to catch const std::exception&

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_append.cpp, test/test_as_container.cpp, test/test_bool_operator.cpp, test/test_choices.cpp, test/test_default_args.cpp, test/test_equals_form.cpp, test/test_get.cpp, test/test_help.cpp, test/test_parse_known_args.cpp, test/test_repr.cpp, test/test_subparsers.cpp
This PR adds in-built support for `.choices()` on arguments
```cpp
#include "argparse.hpp"
int main(int argc, char* argv[]) {
program.add_argument("input")
.default_value("baz")
.choices("foo", "bar", "baz");
try {
program.parse_args(argc, argv);
}
catch (const std::exception& err) {
std::cerr << err.what() << std::endl;
std::cerr << program;
std::exit(1);
}
auto input = program.get("input");
std::cout << input << std::endl;
}
```
```console
foo@bar:/home/dev/$ ./main fex
Invalid argument "fex" - allowed options: {foo, bar, baz}
```
=> Closes #277

samples/CMakeLists.txt
There was a line in samples/CMakeLists.txt which built all samples to the same binary name "tests", which made all the samples override each other while building.
```cmake
function(add_sample NAME)
ADD_EXECUTABLE(ARGPARSE_SAMPLE_${NAME} ${NAME}.cpp)
INCLUDE_DIRECTORIES("../include" ".")
set_target_properties(ARGPARSE_SAMPLE_${NAME} PROPERTIES OUTPUT_NAME ${NAME})
set_target_properties(ARGPARSE_SAMPLE_${NAME} PROPERTIES OUTPUT_NAME tests) # This line overrides the above line
set_property(TARGET ARGPARSE_SAMPLE_${NAME} PROPERTY CXX_STANDARD 17)
endfunction()
```
Simply removing the line:
```cmake
function(add_sample NAME)
ADD_EXECUTABLE(ARGPARSE_SAMPLE_${NAME} ${NAME}.cpp)
INCLUDE_DIRECTORIES("../include" ".")
set_target_properties(ARGPARSE_SAMPLE_${NAME} PROPERTIES OUTPUT_NAME ${NAME}) …
```
=> Fix all samples building to "tests" binary

include/argparse/argparse.hpp
The parse_number structs throw errors through do_from_chars and do_strtod<T> whenever a user enters a numerical argument error, but the errors are extremely undescriptive and give little to no detail on what type or notation was expected.
In order to give more descriptive errors for when parsing numbers fail for this reason, I added try/catch wrappers around the do_from_chars and do_strtod<T> calls in the implemented parse_number templates. Now, the thrown errors will also have a message which displays what type of number the parsed number was expected to be, while maintaining the messages and error types from do_from_chars and do_strtod in the process.
=> More descriptive parse_number errors

CMakeLists.txt, README.md
This pull request comes as a way to make sure users including argparse through FetchContent or through a direct add_subdirectory() call won't have argparse tests built or the argparse install commands configured by default.
Concerning not using the cmake provided [PROJECT_IS_TOP_LEVEL](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html) variable, PROJECT_IS_TOP_LEVEL is not used because it has a required minimum cmake version of 3.21 while argparse uses a minimum cmake version of 3.12.4. 
This approach is largely based on the way [Catch2 handles this same condition (Lines 5-9)](https://github.com/catchorg/Catch2/blob/devel/CMakeLists.txt) in their CMakeLists.txt, as well as [this issue](https://github.com/catchorg/Catch2/issues/1373) which references to glitchy …
=> Set argparse to not run tests or set up install if not top level

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_mutually_exclusive_group.cpp
Create a mutually exclusive group using `program.add_mutually_exclusive_group(required = false)`. `argparse`` will make sure that only one of the arguments in the mutually exclusive group was present on the command line:
```cpp
auto &group = program.add_mutually_exclusive_group();
group.add_argument("--first");
group.add_argument("--second");
```
with the following usage will yield an error:
```console
foo@bar:/home/dev/$ ./main --first 1 --second 2
Argument '--second VAR' not allowed with '--first VAR'
```
The `add_mutually_exclusive_group()` function also accepts a `required` argument, to indicate that at least one of the mutually exclusive arguments is required:
```cpp
auto &group = program.add_mutually_exclusive_group(true);
group.add_argument("--first"); …
```
=> Closes #221

include/argparse/argparse.hpp, test/test_scan.cpp
```cpp
program.add_argument("-n").scan<'b', uint8_t>();
program.parse_args({"test", "-n", "0b101"});
REQUIRE(program.get<T>("-n") == 0b101);
```
=> Added support for binary notation, e.g., 0b101

include/argparse/argparse.hpp, module/argparse.cppm
Currently argparse cannot be built using `ARGPARSE_MODULE_ENABLE_STD_MODULE` macro, because there are two problems.
- In `argparse.hpp`, the header `<cerrno>` should be outside the macro if statement because `errno` macro variable cannot be exported via C++ module.
- In `argparse.cppm`, to use `<cstdlib>` features, `std.compat` module should also be imported.
This PR's commits include these fixes.
=> Fix for C++23 standard library module usage.

include/argparse/argparse.hpp
I'm integrating this fantastic library into a larger project (https://gdal.org) that has a CI configuration building with clang's  ``-fsanitize=unsigned-integer-overflow`` mode, and it currently halts in a few places of argparse. This is apparently due to the std::map<> methods using unsigned integer overflow when they key is a std::string_view, at least with clang 10 on Ubuntu 20.04. Unsigned integer overflow is well defined behavior in C/C++, but I tend to think it is preferable to avoid it to be able to detect real bugs where the overflow is not desired. With those changes, argparse unit test now run fine with ``-fsanitize=unsigned-integer-overflow``
I also find it quite fragile to use a std::string_view as the key of a map. This assumes that the key has a lifetime greater or equal to …
=> Make clang -fsanitize=unsigned-integer-overflow happy

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_hidden_alias.cpp
It is sometimes desirable to offer an alias for an argument, but without it appearing it in the usage. For example, to phase out a deprecated wording of an argument while not breaking backwards compatible. This can be done with the ``ArgumentParser::add_hidden_alias_for()` method.
```cpp
auto &arg = program.add_argument("--suppress").flag();
program.add_hidden_alias_for(arg, "--supress"); // old misspelled alias
```
=> Add a ArgumentParser::add_hidden_alias_for() method

README.md, include/argparse/argparse.hpp, test/CMakeLists.txt, test/test_store_into.cpp
It is possible to bind arguments to a variable storing their value, as an alternative to explicitly calling ``program.get<T>(arg_name)`` or ``program[arg_name]``
This is currently implementeted for variables of type ``bool`` (this also implicitly calls ``flag()``), ``int``, ``double``, ``std::string`` and ``std::vector<std::string>``. If the argument is not specified in the command line, the default value (if set) is set into the variable.
```cpp
bool flagvar = false;
program.add_argument("--flagvar").store_into(flagvar);
int intvar = 0;
program.add_argument("--intvar").store_into(intvar);
double doublevar = 0;
program.add_argument("--doublevar").store_into(doublevar);
std::string strvar;
program.add_argument("--strvar").store_into(strvar);
std::vector<std::string> strvar_repeated; …
```
=> Add Argument::store_into() functions

include/argparse/argparse.hpp
Both changes are needed in the special case of GDAL where our existing
hand-made argument parser accepts positional arguments placed anywhere
in the arguments, not just after optional arguments.
In the GDAL code, in https://github.com/OSGeo/gdal/pull/9445/commits/8bb3455eedb658b55911f33fe272b8045f85f2ec#diff-4592e7daae8543536dbeadf05a3c110282ea0fc089216186138c923a0d4d8000R170 ,
I've implemented a preliminary pass before calling
ArgumentParser::process_args() that re-order arguments. For that, I need
to be able to call consume() but without side-effects (dry_run=False)
and accept members that are private
=> Add a dry_run argument to Argument::consume(), and change ArgumentParser private section to protected

README.md, include/argparse/argparse.hpp, test/test_help.cpp
- Display mutually exclusive arguments as ``[[-a]|[-b]]`` in usage
- Add ... trailer to repeatable arguments in usage: ``[-x]...``
- Implement the following enhancements:
By default usage is reported on a single line.
The ``ArgumentParser::set_usage_max_line_width(width)`` method can be used to display the usage() on multiple line, by defining the maximum line width.
It can be combined with a call to ``ArgumentParser::set_usage_break_on_mutex()`` to ask grouped mutually exclusive arguments to be displayed on a separate line.
``ArgumentParser::add_usage_newline()`` can also be used to force the next
argument to be displayed on a new line in the usage output.
The following snippet
```cpp
argparse::ArgumentParser program("program");
program.set_usage_max_line_width(80); …
```
=> Several bug fixes in usage, and improvement in usage and help

include/argparse/argparse.hpp, test/test_store_into.cpp
Allow store_into() to work with general integer types.
=> Store ints

.bazelrc, .gitignore, BUILD.bazel, README.md, WORKSPACE.bazel, samples/BUILD.bazel, samples/add_sample.bzl, test/BUILD.bazel
I noticed there was a PR to try to add bazel support. My PR doesn't contain non-Bazel-oriented commits and it has been tested on ArchLinux and Windows 11.
=> add Bazel support

include/argparse/argparse.hpp
The argparse.hpp copy inside GDAL has caused Coverity Scan to emit a (false-positive) warning about x not being initialized.
```
________________________________________________________________________________________________________
*** CID 1544814:  Uninitialized variables  (UNINIT)
/gdal/apps/argparse/argparse.hpp: 257 in gdal_argparse::details::do_from_chars<unsigned char, (int)10>(std::basic_string_view<char, std::char_traits<char>>)()
251       if (ec == std::errc::invalid_argument) {
252         throw std::invalid_argument{"pattern '" + std::string(s) + "' not found"};
253       }
254       if (ec == std::errc::result_out_of_range) {
255         throw std::range_error{"'" + std::string(s) + "' not representable"};
256       }
>>>     CID 1544814:  Uninitialized variables  (UNINIT) …
```
=> do_from_chars(): initialize variable to fix Coverity Scan warning

module/argparse.cppm
This PR does:
- Suppress `include-angled-in-module-purview` warning. Export extern "C++" style is valid in Clang (https://clang.llvm.org/docs/StandardCPlusPlusModules.html#export-extern-c-style), but warning is emitted. This commit disables it.
=> Module improvement.

include/argparse/argparse.hpp
This bug [1] causes GCC to emit a wrong warning when adding a short string literal to a std::string. Wrapping the literal in a std::string doesn't have a large impact and avoids the warning.
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105329
---
Fixes #358
=> parse_args(): work around GCC 12 warning bug.

include/argparse/argparse.hpp, test/test_parse_args.cpp
If a non-positional argument doesn't get the number of required values, a generic "Too few arguments" error is generated, without its name, when it is not the last argument (but if it is the last argument, we get its name)
=> Add argument name after 'Too few arguments' error

README.md
* Rename parent_parser -> surface_parser
* The second constructor argument is a string.
=> Correct Parent Parser errors in README.md

CMakeLists.txt
Changed CMakeLists.txt so that users can install argparse when argparse is a subproject (e.g. CMake FetchContent).
=> Allow to install when argparse is a subproject

include/argparse/argparse.hpp
I have pulled the latest release and it doesn't compile because I have a min macro defined in the minwindef.h
This change fixes the problem.
@p-ranav It would be nice if you can use this syntax `(std::numeric_limits<std::size_t>::max)();` in your future releases so I don't need to patch this issue again
Thanks
=> Updated the min and max to deal with a macro in minwindef.h

include/argparse/argparse.hpp, test/test_actions.cpp, test/test_scan.cpp, test/test_store_into.cpp
Also fixes the incompatibility between store_into and scan and action: when the three methods above were called, being all based on the (unique) action, the last one would overwrite the previous ones.
This issue was making the parser strictly dependant on the order of the scan/store_into/action calls making them mutually exclusive.
=> FEATURE: multiple actions

include/argparse/argparse.hpp, test/test_store_into.cpp
Discovered floats didn't work while trying to put in writing to `std::optional<T>` (which still needs work).
=> store_into: Accept float (by accepting generic floating point)
